/**
 * The multiple-choice banks for both tracks, mirrored for local development.
 *
 * GENERATED by scripts/sync-academy-banks.mjs. Edit the questions in the season
 * engine, at src/lib/academy/beginner.ts and intermediate.ts, then run
 * `pnpm banks:sync`. `pnpm copy:check` fails if the two ever disagree.
 *
 * The engine is authoritative: its grader is what decides a real completion.
 * This copy exists so a lesson page still works when the engine is not running,
 * which is the difference between someone being able to edit Academy prose and
 * not. Everything it feeds is issued as an inert `local:` token.
 */

export const QUESTIONS = {
  "what-alchemix-does": [
    {
      prompt:
        "You borrow against a deposit in Alchemix and leave the position alone for a year. " +
        "What brings the balance down?",
      options: [
        "Redemptions, which spend a slice of your own collateral to clear it",
        "The yield your deposit earns, credited against the loan",
        "The protocol, which covers the repayments out of its treasury",
        "Nothing until you repay. The balance holds where you left it",
      ],
      correct: 0,
      explain: [
        "Right. Redemptions convert collateral already earmarked against your debt, so the balance falls out of your own position.",
        "Yield sits on the other side of the position: it raises what your deposit is worth. Redemptions are what clear the debt.",
        "The treasury funds none of this. The collateral spent on your debt is your own, which is why a redemption fee is the only charge.",
        "Leave it alone and it still falls. Redemptions run against every open loan in the market whether or not you touch yours.",
      ],
    },
    {
      prompt:
        "Your loan has been open for three years and you have not touched it. " +
        "What has holding it that long cost you?",
      options: [
        "Nothing for the time itself, and three years of redemptions have been clearing it",
        "Three years of interest, at a rate the DAO sets",
        "Three years of yield, which the protocol kept in exchange for the loan",
        "A share of the deposit, taken when the loan passed its term",
      ],
      correct: 0,
      explain: [
        "Right. Time is the one thing an Alchemix loan never charges for, and three years of redemptions have been clearing the balance the whole way.",
        "The DAO sets a redemption rate, which clears debt rather than adding to it. No rate of any kind adds to an Alchemix balance.",
        "The yield stays with your deposit and raises what it is worth. The loan takes none of it.",
        "An Alchemix loan has no term. It stays open until you close it, and the deposit is untouched for holding it.",
      ],
    },
    {
      prompt:
        "You deposit 10,000 USDC and borrow 5,000 alUSD against it. Where is the 10,000?",
      options: [
        "In the vault, earning, and backing the loan at the same time",
        "In the vault, with 5,000 of it set aside and no longer earning",
        "Half of it was sold to fund the alUSD you borrowed",
        "Held by the protocol until you repay, then returned with the yield",
      ],
      correct: 0,
      explain: [
        "Right. Every unit stays in the vault and keeps earning, and those same units are what secure the loan.",
        "All 10,000 keeps earning. Securing the loan is a second job it does at the same time.",
        "Your deposit is not sold. Borrowing mints alUSD against it, and the 10,000 stays where you put it.",
        "The yield reaches you as the deposit rises in value rather than as a payout at the end, and whatever the cap leaves free can be withdrawn any day.",
      ],
    },
  ],

  "your-deposit": [
    {
      prompt:
        "You deposit 10,000 USDC into a vault on the Borrow page. What does the vault do with it?",
      options: [
        "Wraps it into MYT, a share of a basket of yield strategies the Alchemix DAO manages",
        "Lends it to other Alchemix users, who pay you interest on it",
        "Holds it as USDC until you borrow against it",
        "Sells it for alUSD and holds that instead",
      ],
      correct: 0,
      explain: [
        "Right. Your deposit becomes the Mix-Yield Token, and the DAO picks and rebalances the strategies behind it.",
        "Alchemix lends nothing out. The deposit goes into yield strategies the DAO selects, and what they earn is yours.",
        "The vault puts the USDC to work at once. It becomes MYT and starts earning whether or not you ever borrow.",
        "Your USDC stays USDC underneath. alUSD only exists if you choose to borrow, and the deposit is what backs it.",
      ],
    },
    {
      prompt: "A year on, your deposit has earned 5%. Where does that yield show up?",
      options: [
        "In the value of the MYT you already hold, so each one is worth more USDC",
        "As a USDC payment sent to your wallet at the end of each month",
        "As extra MYT tokens added to your position",
        "As a credit against a loan, if you have one",
      ],
      correct: 0,
      explain: [
        "Right. You hold the same MYT the whole time, and each one is worth a little more of the underlying as the strategies earn.",
        "Nothing is paid out on a schedule. The yield sits in the value of your MYT, and you collect it whenever you withdraw.",
        "The count of MYT stays where it was. What rises is what each one is worth.",
        "Yield stays on the deposit side of a position. Redemptions are what clear a loan.",
      ],
    },
    {
      prompt: "You deposited 10,000 USDC last week and want it back today. What can you withdraw?",
      options: [
        "All of it, plus whatever it has earned, on any day you like",
        "All of it, once a notice period has passed",
        "Only the yield, until the vault's term ends",
        "All of it, minus an early withdrawal fee",
      ],
      correct: 0,
      explain: [
        "Right. The vault has no lock-up, so any amount comes out on any day, and the yield comes with it.",
        "Withdrawals go through the moment you ask. The vault holds no notice period.",
        "The vault has no term. The whole deposit, principal and yield, is available on any day.",
        "Withdrawing from the vault is free. The early exit fee belongs to the Transmuter, which is a different product.",
      ],
    },
    {
      prompt:
        "A vault card on the Borrow page shows its deposit cap is full. What happens if you try to deposit?",
      options: [
        "The vault takes nothing more until the DAO raises the cap",
        "Your deposit waits in a queue until space opens",
        "Your deposit goes in, at a lower yield",
        "Your deposit is routed to another vault automatically",
      ],
      correct: 0,
      explain: [
        "Right. A full cap closes the vault to new deposits, and the bar on the card shows how close it is.",
        "There is no deposit queue. A full vault is closed until the DAO raises its cap.",
        "The cap is a hard limit on what the vault holds, so nothing more goes in at any yield.",
        "Nothing is routed for you. You pick the vault, and a full one is closed until the cap moves.",
      ],
    },
  ],

  "borrowing": [
    {
      prompt:
        "Your 10,000 USDC is in the vault. You open the Borrow tab and press Max. What happens?",
      options: [
        "9,000 alUSD is minted to your wallet, and the 10,000 stays in the vault earning",
        "9,000 USDC is sent from the vault to your wallet",
        "10,000 alUSD is minted, since the deposit backs it one for one",
        "9,000 alUSD is minted, and 9,000 of the deposit stops earning",
      ],
      correct: 0,
      explain: [
        "Right. Borrowing mints alUSD against the deposit, up to 90% of it, and the deposit itself does not move.",
        "Borrowing mints a new token, alUSD, rather than releasing your USDC. The deposit stays in the vault.",
        "The cap is 90% of the deposit, so 10,000 of collateral backs at most 9,000 alUSD.",
        "Every unit of the deposit keeps earning with a loan against it. Backing the loan is a second job it does at the same time.",
      ],
    },
    {
      prompt: "What does your LTV measure?",
      options: [
        "What you owe divided by what you deposited",
        "Your deposit divided by your debt",
        "The share of your deposit that is still earning",
        "How much more you are allowed to borrow",
      ],
      correct: 0,
      explain: [
        "Right. Borrow 3,000 against 10,000 and your LTV is 30%. Alchemix caps it at 90%.",
        "That is the ratio upside down. LTV is loan to value: the debt over the deposit, so 3,000 against 10,000 is 30%.",
        "The whole deposit earns whatever your LTV is. LTV is the debt as a share of the deposit.",
        "Borrowing room is what the app calls Borrowable. LTV is what you owe as a share of what you deposited.",
      ],
    },
    {
      prompt: "Your vault shows a health factor of 3.00. What is it telling you?",
      options: [
        "Your LTV is a third of the 90% cap, so you are at 30%",
        "You can borrow three times your deposit",
        "Your deposit is worth three times your debt",
        "You have three days before liquidation",
      ],
      correct: 0,
      explain: [
        "Right. Health factor is the borrowing cap divided by your LTV: 90% over 30% is 3.00, and it reads 1.00 at the cap.",
        "Borrowing stops at 90% of the deposit, never above it. Health factor is how far under that cap you sit.",
        "Close, but the figure is measured against the 90% cap rather than against the deposit. At 30% LTV the deposit is 3.33 times the debt, and the health factor is 3.00.",
        "Health factor has no clock in it. It compares your LTV with the borrowing cap, and only a loss inside the vault can move you toward liquidation.",
      ],
    },
    {
      prompt: "After borrowing, 5,000 alUSD sits in your wallet. What is it?",
      options: [
        "A token minted against your deposit. Sell it for dollars, or hand it back to repay",
        "5,000 USDC released from your deposit",
        "A receipt you return to the vault when you want your deposit back",
        "Your share of the vault, the same thing as MYT",
      ],
      correct: 0,
      explain: [
        "Right. alUSD is a new token minted against the collateral. It trades a little under a dollar, and inside Alchemix one alUSD cancels one USDC of debt.",
        "Your USDC never left the vault. alUSD is a separate token, created when you borrowed.",
        "alUSD is the loan rather than a receipt. Repaying it cancels debt, and withdrawing the deposit is a separate step.",
        "MYT is what your deposit became, and it stays in the vault. alUSD is the debt you minted against it.",
      ],
    },
  ],

  "self-repaying": [
    {
      prompt:
        "Your vault shows a redemption rate of 70%. You owe 5,000 and you leave the position " +
        "alone for a year. What is that rate measuring?",
      options: [
        "About 70% of what you owe gets cleared over the year, and you do nothing to make it happen",
        "Your collateral earns about 70% over the year",
        "You can borrow up to 70% of what you deposited",
        "About 70% of your collateral is set aside and can no longer be withdrawn",
      ],
      correct: 0,
      explain: [
        "Right. The rate is the share of your debt that redemptions clear in a year, and the protocol applies it whether or not you act.",
        "What your collateral earns is the vault's APR, a separate figure on the same screen. The redemption rate measures repayment.",
        "Borrowing is capped at 90% of the deposit. The redemption rate is the pace your debt clears at.",
        "Earmarked is the figure for collateral reserved against a coming redemption, and it keeps earning until the claim settles.",
      ],
    },
    {
      prompt: "You want the loan cleared sooner than redemptions will clear it. What can you do?",
      options: [
        "Repay it yourself, in any amount, on any day",
        "Deposit more collateral, which raises the rate applied to your position",
        "Put the alUSD you borrowed into the Transmuter and wait out the term",
        "Wait for the earmarked slice to settle, which is the only repayment open to you",
      ],
      correct: 0,
      explain: [
        "Right. Repaying is open on any day, and the collateral it was holding frees up immediately.",
        "More collateral lowers your LTV and buys you borrowing room. The redemption rate is set for the whole market and does not move with one position.",
        "That is the saver's route, and it would leave you waiting out a term for USDC while still carrying the debt. Inside Alchemix one alUSD cancels one of debt today.",
        "Redemptions set the pace for a position you leave alone. Repaying by hand runs alongside them and takes effect at once.",
      ],
    },
    {
      prompt:
        "Over one year your deposit earned 5% and redemptions cleared part of your debt. " +
        "Which side of the position moved?",
      options: [
        "Both, independently: the deposit is worth more and the debt is smaller",
        "Only the debt, because the yield is what funded the redemptions that cleared it",
        "Only the deposit, because the debt waits for you to repay it",
        "Both, and by the same amount, because the yield is applied to the debt",
      ],
      correct: 0,
      explain: [
        "Right. Yield raises the collateral side, redemptions lower the debt side, and neither one drives the other.",
        "Redemptions are funded by the Transmuter queue, which earmarks collateral. Your yield stays with your deposit.",
        "The debt is paid down without you. Redemptions clear a share of it every year whether or not you act.",
        "They are separate figures with separate causes. What the strategies earn has no bearing on how much gets repaid.",
      ],
    },
  ],

  "what-can-go-wrong": [
    {
      prompt: "Which of these can move an Alchemix position toward liquidation?",
      options: [
        "A strategy inside your vault losing money, which leaves the same debt against less collateral",
        "A sharp fall in the price of ETH, which lowers what your collateral is worth",
        "The redemption rate falling, which slows the repayment of your debt",
        "alUSD trading at 0.95, which leaves your debt worth more than your collateral",
      ],
      correct: 0,
      explain: [
        "Right. A loss of backing is the one thing that moves your LTV, because the debt is unchanged while the collateral behind it falls.",
        "A price fall moves both sides at once. Your debt is recorded in alETH and your collateral is ETH, so the ratio between them holds.",
        "A slower rate leaves the debt in place for longer. It does not raise your LTV, which is the ratio liquidation measures.",
        "The protocol counts one alUSD as one USDC of debt whatever an exchange is charging, so a market price cannot move your ratio.",
      ],
    },
    {
      prompt: "Your position reaches the 90% borrowing cap. What happens next?",
      options: [
        "Borrowing stops. Everything else about the position carries on as it was",
        "The protocol starts selling collateral to bring the ratio back under the cap",
        "The deposit stops earning until the ratio comes back down",
        "Redemptions stop, because the position has no room left",
      ],
      correct: 0,
      explain: [
        "Right. The cap limits borrowing and does nothing else. Liquidation is a separate mechanism at 95%, and a loss of backing is what carries you there.",
        "Selling starts at the liquidation threshold of 95%. The cap at 90% stops further borrowing and leaves the position open.",
        "Your collateral earns at the cap exactly as it did below it.",
        "Redemptions carry on clearing your debt, which moves you away from the cap rather than toward it.",
      ],
    },
    {
      prompt:
        "You deposit 4 ETH and borrow 2 alETH against it. Overnight ETH falls from 3,000 to 1,800. " +
        "What is your LTV in the morning?",
      options: [
        "50%, exactly where it started",
        "83%, because the collateral is worth less and the debt is unchanged",
        "30%, because the debt fell further than the collateral did",
        "It depends on what alETH is trading at against ETH that morning",
      ],
      correct: 0,
      explain: [
        "Right. 2 alETH against 4 ETH is 50% at any price, because the price divides out of both sides.",
        "That is how it works where the debt is a dollar amount. Here you owe 2 alETH, and 2 alETH is worth less in the morning too.",
        "Both sides fell by the same proportion, so neither the ratio nor your borrowing room moved.",
        "The protocol counts 1 alETH as 1 ETH of debt for this. What an exchange charges is between you and whoever you sell to.",
      ],
    },
  ],

  "the-transmuter": [
    {
      prompt:
        "You buy 5,000 alUSD for 4,800 USDC, deposit it in the Transmuter, and wait the full term. " +
        "What do you receive?",
      options: [
        "5,000 USDC worth, so the 200 you saved on the purchase is the return",
        "4,800 USDC worth, the amount you put in, plus the yield it earned while it waited",
        "5,000 USDC worth, plus the yield your alUSD earned in the queue",
        "Whatever 5,000 alUSD is trading for on the day it matures",
      ],
      correct: 0,
      explain: [
        "Right. The exchange is 1:1 on face value, so buying below 1.00 is where the whole return comes from.",
        "The exchange settles on face value rather than on what you paid. 5,000 alUSD redeems for 5,000 USDC worth.",
        "Your alAssets sit in the queue without earning. Buying below 1.00 and receiving 1.00 is the entire return.",
        "The market price stops mattering at maturity. The Transmuter exchanges at exactly 1:1.",
      ],
    },
    {
      prompt: "What decides how long you wait for a Transmuter deposit to mature?",
      options: [
        "A term the Alchemix DAO sets, which differs by asset and by chain",
        "How much alUSD is already waiting in the queue ahead of you",
        "The size of your deposit, with larger deposits settling in stages",
        "The redemption rate, which sets how fast the queue clears",
      ],
      correct: 0,
      explain: [
        "Right. The DAO sets the term and adjusts it over time, so read the current one on the card before you deposit.",
        "The size of the queue does move the redemption rate that borrowers see. Your own wait is the fixed term on the card.",
        "Every deposit waits the same set term, whatever its size.",
        "The rate moves with the queue and governs how fast borrower debt clears. Your wait is the term the DAO set.",
      ],
    },
    {
      prompt:
        "You deposit alUSD in the Transmuter and then need the funds before the term is up. " +
        "What are your options?",
      options: [
        "Leave the queue early and pay the early exit fee",
        "Wait it out. The deposit is committed until it matures",
        "Swap your place in the queue with someone further forward",
        "Withdraw at no cost, since the fee applies to the redemption rather than the exit",
      ],
      correct: 0,
      explain: [
        "Right. The exit is open on any day, and the fee exists to keep deposits committed for the term.",
        "You are never committed. Leaving is available whenever you need it, and the fee is what it costs.",
        "Queue positions are not traded between users. You exit your own deposit and pay the fee.",
        "The fee is charged on the early exit itself. Waiting out the term is the route that costs you nothing.",
      ],
    },
  ],

  "getting-money-back": [
    {
      prompt:
        "A position holds 10,000 of collateral against 5,000 of debt, and the app shows " +
        "4,444 free to withdraw rather than 5,000. What is the other 556 doing?",
      options: [
        "Backing the debt, which needs 5,556 behind it to stay under the 90% cap",
        "Covering a fee charged when collateral leaves the position",
        "Held back until the next redemption cycle settles",
        "Earning yield that has not been credited to the position yet",
      ],
      correct: 0,
      explain: [
        "Yes. Debt can be at most 90% of collateral, so 5,000 of debt reserves 5,556. Everything above that is free.",
        "Withdrawing what is already free costs nothing. The gap is collateral the cap reserves, not a charge.",
        "Withdrawals are not on a cycle. You can take the free collateral any day, and what stays behind is set by the cap.",
        "Yield raises the value of the whole deposit. The gap is the collateral the 90% cap reserves against the debt.",
      ],
    },
    {
      prompt: "You repay 1,000 of an open loan. How much collateral does that free?",
      options: [
        "About 1,111, because each unit of debt reserves about 1.11 of collateral",
        "Exactly 1,000, one for one",
        "900, because the cap is 90%",
        "Nothing, until the loan is cleared in full",
      ],
      correct: 0,
      explain: [
        "Right. At a 90% cap, 1 of debt holds 1 / 0.9 of collateral, so clearing 1 of debt releases about 1.11.",
        "Repaying frees more than it clears. A unit of debt reserves 1.11 units of collateral, and that is what comes free.",
        "That inverts the cap. Debt is 90% of collateral, so collateral is 1 / 0.9 of debt: about 1.11.",
        "Collateral frees up with every repayment, not only once the last of the debt is gone.",
      ],
    },
    {
      prompt: "When can you withdraw the collateral the app shows as free?",
      options: [
        "Any day, with nothing to repay first",
        "Only once the loan is repaid in full",
        "Only at the end of a redemption cycle",
        "Only once the deposit has earned enough to cover the debt",
      ],
      correct: 0,
      explain: [
        "Right. Whatever the app shows as free can leave today. Repaying first is a choice, not a requirement.",
        "Repaying frees more collateral, but whatever is already free can leave today.",
        "Redemption cycles clear debt. They have nothing to do with when you can withdraw.",
        "Yield raises what the deposit is worth. What is free to withdraw is whatever sits above what the cap reserves.",
      ],
    },
    {
      prompt:
        "Two positions each hold 20,000 of collateral. One owes 5,000, the other owes 15,000. " +
        "Which has more free to withdraw?",
      options: [
        "The one owing 5,000, because a smaller debt reserves less collateral",
        "Both the same, because the cap applies to the collateral, not the debt",
        "The one owing 15,000, because a larger loan has drawn more yield",
        "Neither, because collateral is locked while any debt is open",
      ],
      correct: 0,
      explain: [
        "Yes. Reserved collateral is the debt divided by 0.9, so a smaller debt leaves more free.",
        "The cap ties the two together. What is reserved is set by the debt: 5,556 against 5,000, 16,667 against 15,000.",
        "Yield accrues to the deposit, not to the loan. It does not change what the cap reserves.",
        "Collateral above what the cap reserves is free at any time, whether or not debt is open.",
      ],
    },
  ],

  "pace-of-repayment": [
    {
      prompt:
        "Ana borrows 2,000 and Ben borrows 8,000 against identical deposits on the same day. " +
        "Both leave the position alone for a year. What is true at the end of it?",
      options: [
        "The same share of each loan is left, because one redemption rate applies to both",
        "Ana is further along, because a smaller loan clears sooner",
        "Ben is further along, because a larger loan draws more redemptions",
        "Neither has moved, because redemptions only run when you ask for them",
      ],
      correct: 0,
      explain: [
        "Right. The redemption rate is a share of debt, not an amount, so it applies to both loans equally.",
        "That is how an interest-bearing loan behaves. Alchemix charges no interest, and the rate is a share of what you owe.",
        "Redemptions are proportional. More of Ben's loan is cleared in absolute terms, but not a larger share of it.",
        "Redemptions run whether or not you touch the position. That is what makes the loan self-repaying.",
      ],
    },
    {
      prompt: "Which of these changes how fast redemptions clear your debt?",
      options: [
        "The redemption rate, which the protocol sets for the whole market",
        "The size of your loan",
        "The yield your vault earns",
        "The LTV you opened at",
      ],
      correct: 0,
      explain: [
        "Yes. It is the one input that moves the curve, and it is the same figure for every position in the market.",
        "Loan size changes the amount cleared, not the pace. The same share of a large loan and a small one goes each year.",
        "Yield raises what your MYT is worth. Redemptions are what clear the debt, and the two are separate.",
        "Your LTV sets how much room you have before a loss reaches you. It does not change the pace of repayment.",
      ],
    },
    {
      prompt: "The protocol raises the redemption rate. What happens to a position already open?",
      options: [
        "Its debt clears faster, at the new rate, along with every other position",
        "It keeps the rate it opened at, and only new positions use the new one",
        "Its collateral is sold faster to fund the difference",
        "Nothing, unless the borrower opts in",
      ],
      correct: 0,
      explain: [
        "Right. The rate is a protocol-level parameter applied to the whole market at once, not a term of your loan.",
        "There is no rate attached to a position. There is one rate, and it applies to everyone.",
        "Redemptions convert collateral already earmarked against the debt. Nothing extra is sold to keep up.",
        "There is nothing to opt in to. The rate applies to the whole market, and repaying by hand is the part you choose.",
      ],
    },
    {
      prompt: "You want the loan gone sooner than redemptions will clear it. What can you do?",
      options: [
        "Repay by hand, in any amount, whenever you like",
        "Raise the redemption rate on your own position",
        "Borrow more, which raises the rate applied to you",
        "Nothing. The pace is fixed for everyone",
      ],
      correct: 0,
      explain: [
        "Exactly. The rate is not yours to set, but repaying is always open and takes effect immediately.",
        "The rate is a market-wide parameter. There is no per-position setting for it.",
        "Borrowing more raises what you owe. It does not speed anything up.",
        "The rate is fixed for everyone, but repaying by hand is not.",
      ],
    },
  ],

  "where-yield-comes-from": [
      {
        prompt: "Why do the DAO's risk caps on an MYT matter to someone borrowing against it?",
        options: [
          "They bound the worst loss the vault can take, which is what makes a given LTV safe",
          "They cap how much you are allowed to borrow",
          "They set the yield your deposit earns",
          "They decide which asset you can repay with",
        ],
        correct: 0,
        explain: [
          "Right. A loss of backing is the one thing that can liquidate you, and the caps are what bound the size of a plausible one.",
          "Borrowing is capped at 90% of collateral. The risk caps govern what the vault may hold, not what you may take.",
          "The strategies set the yield. The caps limit how much of the riskiest ones the vault can hold.",
          "Which asset repays depends on whether the debt is earmarked. The risk caps are about vault composition.",
        ],
      },
      {
        prompt:
          "An MYT holds one strategy of each class, and Aggressive is filled to its 20% ceiling. " +
          "How much can the Moderate strategy hold?",
        options: [
          "40%, because Moderate and Aggressive share a 60% ceiling",
          "60%, because that is the Moderate ceiling",
          "20%, because Moderate can never hold more than Aggressive",
          "80%, because only Aggressive carries a cap",
        ],
        correct: 0,
        explain: [
          "Yes. The all-strategies figure covers that class and every riskier one, so the 60% is Moderate plus Aggressive.",
          "The 60% is shared. Aggressive is already inside it, so 40% is what remains for Moderate.",
          "There is no rule ordering the two. Moderate is bounded by its own 40% and by the 60% it shares with Aggressive.",
          "Both carry caps. Moderate is capped at 40% on its own and at 60% together with Aggressive.",
        ],
      },
      {
        prompt:
          "Three strategies are proposed: Conservative at 4%, Moderate at 7%, Aggressive at 15%. " +
          "Which composition pays most without breaching a cap?",
        options: [
          "40% Conservative, 40% Moderate, 20% Aggressive",
          "0% Conservative, 60% Moderate, 40% Aggressive",
          "20% Conservative, 40% Moderate, 40% Aggressive",
          "60% Conservative, 20% Moderate, 20% Aggressive",
        ],
        correct: 0,
        explain: [
          "Right. Aggressive fills its 20%, Moderate takes the 40% left of the shared 60%, and Conservative absorbs the rest.",
          "Aggressive is capped at 20%, and Moderate and Aggressive together at 60%. This breaches both.",
          "Aggressive is capped at 20%. Doubling it is not something the DAO could allocate.",
          "This one is legal but not the best available: Moderate can go to 40% before the shared ceiling binds.",
        ],
      },
      {
        prompt:
          "A run of withdrawals shrinks an MYT until its Aggressive strategy is 24% of what is left, " +
          "above the 20% cap. What follows?",
        options: [
          "The allocation stays above its cap until the DAO rebalances, because caps are checked when the DAO allocates",
          "The vault is sold down to the cap automatically",
          "Withdrawals are blocked until the composition is legal again",
          "Nothing, because the caps only apply when an MYT is first created",
        ],
        correct: 0,
        explain: [
          "Exactly. The caps are relative to vault size and are enforced at allocation, so a shrinking vault can drift above one.",
          "Nothing sells automatically. Rebalancing is a DAO action.",
          "Withdrawals are never gated on composition. Your collateral stays yours to take.",
          "The caps govern every allocation, not just the first. They are not re-checked on every withdrawal.",
        ],
      },
    ],

  "cost-of-borrowing": [
    {
      prompt: "You want 10,000 of spendable USDC, and alUSD is trading at 0.98. What do you borrow?",
      options: [
        "More than 10,000, because each alUSD sells for less than a dollar",
        "Exactly 10,000, because debt is recorded at face value",
        "Less than 10,000, because the discount works in your favor",
        "10,000, with the discount charged later as a fee",
      ],
      correct: 0,
      explain: [
        "Right. At 0.98 you need about 10,204 alUSD to walk away with 10,000, and 10,204 is the debt recorded.",
        "Debt is recorded at face value, which is exactly why you have to borrow more than you want to raise.",
        "The discount is a cost to a borrower and a gain to a buyer. You are the one selling below par.",
        "Nothing is charged later. You receive less than face value when you sell.",
      ],
    },
    {
      prompt: "You mint 1,000 alUSD and sell it at 0.97. What debt is recorded against your position?",
      options: [
        "1,000, because debt is recorded at face value whatever you sold for",
        "970, the amount you received",
        "1,030, so the discount is covered",
        "It depends on what alUSD is trading at when you repay",
      ],
      correct: 0,
      explain: [
        "Yes. The market price is between you and the buyer. Inside Alchemix, 1 alUSD is always 1 of debt.",
        "You received 970, but you minted 1,000, and 1,000 is what the position owes.",
        "Nothing is added. The discount is what you gave up on the sale, not something charged on top.",
        "The price never enters it. One alUSD cancels one of debt on any day, at any price.",
      ],
    },
    {
      prompt: "What does an Alchemix loan charge you for holding it longer?",
      options: [
        "Nothing. There is no interest and no charge for time",
        "A variable rate the DAO sets each period",
        "A fixed rate agreed when you borrow",
        "A rate that rises as your LTV rises",
      ],
      correct: 0,
      explain: [
        "Right. Time only works in your favor here: redemptions clear the balance while the collateral earns.",
        "There is no rate of any kind. What the DAO sets is the redemption rate, which clears debt rather than adding to it.",
        "No rate is agreed. The costs are the discount when you sell and the fees tied to specific events.",
        "LTV governs your borrowing room and your distance from the threshold. It does not price the loan.",
      ],
    },
    {
      prompt: "Which of these is a real cost of borrowing in Alchemix?",
      options: [
        "The discount you take when you sell alUSD below face value",
        "Interest accruing on the balance",
        "A daily fee while the position stays open",
        "A penalty for repaying early",
      ],
      correct: 0,
      explain: [
        "Exactly. It is paid once, up front, in the gap between what you mint and what you receive.",
        "There is none. The balance never rises unless you borrow again.",
        "Costs here are tied to events, never to the calendar. Holding a position costs nothing.",
        "Repaying early is free and frees collateral immediately. There is no penalty for it.",
      ],
    },
  ],

  "ltv-and-risk": [
    {
      prompt: "What should decide the highest LTV you open at?",
      options: [
        "The largest loss of backing the vault could plausibly take, which the DAO's risk caps bound",
        "How far you expect the price of your collateral to fall",
        "The redemption rate, since it sets how fast you deleverage",
        "The 90% borrowing cap, which is also the liquidation threshold",
      ],
      correct: 0,
      explain: [
        "Right. A loss of backing is the only thing that can reach you, and the caps are what make that worst case finite.",
        "Price cannot liquidate an Alchemix position. Debt and collateral are the same kind of asset and move together.",
        "The rate sets how quickly the debt clears. It has no bearing on how much loss you can absorb.",
        "They are different numbers. The cap is 90% and stops further borrowing; liquidation begins at 95%.",
      ],
    },
    {
      prompt: "Your position sits at 50% LTV and the MYT reports a 20% loss of backing. What follows?",
      options: [
        "Your LTV moves to 62.5% and the position is untouched, because the threshold is still above it",
        "You are liquidated, because any loss of backing crosses the threshold",
        "Nothing changes, because a loss inside the vault does not affect your LTV",
        "Your debt is written down by 20% to match the collateral",
      ],
      correct: 0,
      explain: [
        "Yes. The same debt now stands against 80% of the collateral, and 50 / 0.8 is 62.5, well under the 95% threshold.",
        "Only a loss large enough to push your LTV past 95% does that. At 50% you have a lot of room.",
        "It does. Your collateral is worth less while the debt is unchanged, so the ratio between them moves.",
        "Debt is unchanged by a loss of backing. That is exactly why the ratio moves against you.",
      ],
    },
    {
      prompt: "A position does cross the liquidation threshold. What does the protocol sell?",
      options: [
        "Only enough to bring the position back to a safe ratio",
        "The whole deposit, closing the position",
        "Enough to clear the debt in full",
        "Nothing, until the borrower chooses to act",
      ],
      correct: 0,
      explain: [
        "Right. It is the minimum needed to restore a healthy LTV, and everything above that is untouched.",
        "Nothing forces a position to close. What is sold is the minimum that restores a safe ratio.",
        "The debt is not cleared. Enough collateral is used to bring the ratio back under the cap, and no more.",
        "Past the threshold the protocol acts without waiting. What it sells is the minimum, not everything.",
      ],
    },
    {
      prompt: "Why can a 40% fall in the price of ETH not liquidate an alETH loan?",
      options: [
        "Debt and collateral are the same kind of asset, so both sides fall together and the ratio holds",
        "The protocol pauses liquidations while the market is moving sharply",
        "The oracle averages the price over a long enough window to absorb it",
        "The 90% cap leaves enough room to absorb a fall that size",
      ],
      correct: 0,
      explain: [
        "Exactly. 4 ETH behind 2 alETH is a 50% LTV at any price, because the price divides out of both sides.",
        "Nothing is paused. The ratio does not move when the price does.",
        "No averaging is needed. Both sides are denominated in the same asset, so the ratio is price-independent.",
        "Room is not what saves you. Even a 90% fall would leave the LTV exactly where it started.",
      ],
    },
  ],

  "transmuter-and-peg": [
    {
      prompt:
        "alUSD is trading at 0.97 and redeems 1:1 at maturity. One market has a 10-week term and " +
        "another a 30-week term. Which pays more, annualized?",
      options: [
        "The 10-week term, because the same discount is collected three times as often",
        "The 30-week term, because you are paid for waiting longer",
        "The same, because the discount is the same",
        "Neither. The Transmuter pays a rate the DAO sets, not one the discount sets",
      ],
      correct: 0,
      explain: [
        "Right. The gain per term is identical, so the shorter wait is worth three times as much over a year.",
        "Waiting longer for the same 3.09% is worth less per year, not more.",
        "The gain over one term is the same. Annualized, how long you wait for it is the whole difference.",
        "The DAO sets the term. What you earn is set by the price you buy at, which is why a wider discount pays more.",
      ],
    },
    {
      prompt: "Why does alUSD trading below a dollar tend to pull the price back up?",
      options: [
        "The Transmuter guarantees 1:1 at maturity, so a wide discount pays well enough to attract buyers",
        "The DAO buys alUSD on the open market whenever it trades below par",
        "The protocol stops minting alUSD until the price recovers",
        "Borrowers are charged a fee whenever the price is below par",
      ],
      correct: 0,
      explain: [
        "Yes. The wider the gap, the better the fixed return for waiting it out, and that buying is what closes it.",
        "No one is required to buy. The peg holds because waiting out the term pays, not because of intervention.",
        "Minting is not gated on the price. What restores the price is buyers taking the discount.",
        "No such fee exists. The discount is a cost a borrower takes when selling, not an ongoing charge.",
      ],
    },
    {
      prompt: "You hold alUSD and you also have an open Alchemix loan. What is the direct way to use it?",
      options: [
        "Repay the loan with it. One alUSD cancels one of debt, immediately",
        "Deposit it in the Transmuter and wait out the term for USDC",
        "Sell it on Curve, then repay with the USDC",
        "Either route is the same, since both settle 1:1",
      ],
      correct: 0,
      explain: [
        "Right. The Transmuter is a fixed-yield product for savers. A borrower holding alUSD already holds what cancels the debt.",
        "That is the saver's route. It would mean waiting out a term for USDC while still carrying the debt.",
        "Selling means taking the discount on something you could have used to repay directly.",
        "They are not the same. Repaying settles today, and the Transmuter settles at the end of a term.",
      ],
    },
    {
      prompt: "What backs the Transmuter's 1:1 exchange?",
      options: [
        "Borrower collateral inside the Alchemist, earmarked against the alUSD waiting in the queue",
        "A reserve the DAO funds out of protocol fees",
        "Liquidity in external pools such as Curve and Balancer",
        "New alUSD minted when a redemption comes due",
      ],
      correct: 0,
      explain: [
        "Exactly. Every alAsset in the queue earmarks an equal value of collateral, and at maturity that collateral settles the claim.",
        "There is no separate reserve. The backing is the collateral of borrowers whose debt the redemption repays.",
        "External pools give you the market price today. The 1:1 guarantee comes from collateral inside the protocol.",
        "Minting more would defeat the point. Redemptions burn alUSD, they do not create it.",
      ],
    },
  ],

  "capstone": [
    {
      prompt:
        "You want a fixed amount of spendable capital, alUSD trades below par, and the vault could " +
        "lose backing. Which two things set the smallest deposit you can open with?",
      options: [
        "How much you must borrow once the discount is accounted for, and the highest LTV that survives the loss",
        "The redemption rate and the length of the transmutation term",
        "The price of your collateral and the 90% borrowing cap",
        "The vault's blended APR and the redemption fee",
      ],
      correct: 0,
      explain: [
        "Right. The deposit is the borrow you need, divided by the LTV that survives the loss.",
        "Those govern how fast the debt clears afterwards. Neither changes the size you have to open at.",
        "Price does not enter it: debt and collateral move together. The loss is what limits you, not the cap.",
        "Both are real, and neither sizes the position. They affect what it earns and what deleveraging costs.",
      ],
    },
    {
      prompt: "alUSD is trading lower than you assumed. What happens to the deposit you need?",
      options: [
        "It rises, because you have to borrow more alUSD to raise the same cash",
        "It falls, because your debt is worth less on the market",
        "Nothing, because the deposit is set by the loss you are sizing against",
        "It rises, because a low price raises the liquidation threshold",
      ],
      correct: 0,
      explain: [
        "Yes. A wider discount means more debt for the same cash, and more debt needs more collateral behind it.",
        "Debt is recorded at face value. What it trades at does not reduce what you owe.",
        "The loss sets the LTV you can carry. The price sets how much you must borrow, and both move the deposit.",
        "The threshold is fixed at 95%. The price moves how much you borrow, not where liquidation sits.",
      ],
    },
    {
      prompt: "The loss you are sizing against doubles. What happens to the LTV you can safely open at?",
      options: [
        "It falls, so the same borrow needs a larger deposit behind it",
        "It rises, because a larger loss frees more collateral",
        "Nothing, because the liquidation threshold is fixed at 95%",
        "It falls, and the 90% borrowing cap falls with it",
      ],
      correct: 0,
      explain: [
        "Right. The threshold applies to the backing that survives, so a larger loss leaves less room to start with.",
        "A loss reduces backing. It never frees collateral.",
        "The threshold is fixed, but the collateral it applies to is not. A larger loss leaves less of it.",
        "The borrowing cap does not move. What moves is how much of it you can safely use.",
      ],
    },
    {
      prompt: "Three of these change the deposit you need. Which one does not?",
      options: [
        "A fall in the market price of your collateral",
        "A wider discount on alUSD",
        "A larger loss of MYT backing",
        "A larger amount of capital you want to raise",
      ],
      correct: 0,
      explain: [
        "Exactly. Price moves debt and collateral together, so it cancels out of the sizing entirely.",
        "A wider discount does move it: you borrow more to raise the same cash, so you deposit more.",
        "A larger loss does move it: the survivable LTV falls, so the same borrow needs more behind it.",
        "Raising more capital does move it: more borrow, and proportionally more deposit.",
      ],
    },
  ],
};

/**
 * The same deterministic shuffle the engine uses, so a locally generated question
 * behaves the way the deployed one does.
 *
 * Returns display position to original index.
 */
export function permutation(n, seed) {
  const order = Array.from({ length: n }, (_, i) => i);

  let state = (Math.abs(Math.trunc(seed)) % 2147483647) + 1;
  const next = () => {
    state = (state * 1664525 + 1013904223) % 4294967296;
    return state / 4294967296;
  };

  for (let i = n - 1; i > 0; i -= 1) {
    const j = Math.floor(next() * (i + 1));
    [order[i], order[j]] = [order[j], order[i]];
  }
  return order;
}
