/**
 * The multiple-choice banks for both tracks, mirrored for local development.
 *
 * GENERATED by scripts/sync-academy-banks.mjs. Edit the questions in the season
 * engine, at src/lib/academy/beginner.ts and intermediate.ts, then run
 * `pnpm banks:sync`. `pnpm copy:check` fails if the two ever disagree.
 *
 * The engine is authoritative: its grader is what decides a real completion.
 * This copy exists so a lesson page still works when the engine is not running,
 * which is the difference between someone being able to edit Academy prose and
 * not. Everything it feeds is issued as an inert `local:` token.
 */

export const QUESTIONS = {
  "what-alchemix-does": [
    {
      prompt: "You borrow against a deposit in Alchemix and then leave it alone. What happens to the amount you owe?",
      options: [
        "It goes down over time, without you doing anything",
        "It goes up, because interest is added to the balance",
        "It stays exactly the same until you repay it",
        "It moves up and down with the market price of your collateral",
      ],
      correct: 0,
      explain: [
        "Right. Redemptions repay it out of your own collateral, so the balance falls while you do nothing.",
        "Alchemix charges no interest. The only direction that balance moves on its own is down.",
        "The balance does not sit still. Redemptions repay it from your collateral the whole time the loan is open.",
        "The amount you owe is recorded in alUSD or alETH and does not follow the market price of your collateral.",
      ],
    },
    {
      prompt: "What are you charged for an Alchemix loan?",
      options: [
        "No interest. The protocol pays the loan down for you over time",
        "A variable rate that rises when more people are borrowing",
        "A fixed annual rate, agreed at the moment you borrow",
        "A daily fee for every day the loan stays open",
      ],
      correct: 0,
      explain: [
        "Right. An Alchemix loan has no interest rate at all.",
        "There is no variable rate here, or any rate at all. Redemptions pay the loan down instead of a lender charging you.",
        "There is no fixed rate either. An Alchemix loan carries no rate of any kind.",
        "Nothing is charged per day. Hold the loan for a decade and redemptions still only push the balance down.",
      ],
    },
    {
      prompt: "What happens to your deposit while a loan is open against it?",
      options: [
        "It stays in the vault and keeps earning the whole time",
        "It is locked and stops earning until the loan is repaid",
        "It is sold, and the proceeds are handed to you as the loan",
        "It is lent out to other users and returned when you repay",
      ],
      correct: 0,
      explain: [
        "Exactly. Your deposit stays in the vault and keeps earning the whole time it backs the loan.",
        "It keeps earning the whole time. An open loan gives your deposit a job as collateral, and it keeps earning in that job.",
        "Nothing is sold. You keep your deposit, and it keeps earning while the loan is open.",
        "Your deposit is not lent to anyone. It stays yours and keeps earning in the vault.",
      ],
    },
  ],

  "self-repaying": [
    {
      prompt: "Starting from an open loan you leave alone, which of these makes the amount you owe go up?",
      options: [
        "Borrowing more against the same position",
        "Time passing",
        "The price of your collateral falling",
        "Yield accruing in the vault",
      ],
      correct: 0,
      explain: [
        "Right. Borrowing more is the only thing that raises what you owe.",
        "Time alone lowers the balance, because redemptions keep clearing a little more of it for you.",
        "A price move does not change what you owe. Your debt is recorded in alUSD or alETH, and that number does not follow the price of your collateral.",
        "Yield works in your favor. It never raises what you owe.",
      ],
    },
    {
      prompt: "You want your loan cleared sooner than the protocol will clear it on its own. What can you do?",
      options: [
        "Repay some or all of it yourself, at any time",
        "Nothing. The schedule is fixed once the loan is open",
        "Borrow more, which speeds up the rate of repayment",
        "Withdraw collateral, which forces an early repayment",
      ],
      correct: 0,
      explain: [
        "Yes. You can repay any amount whenever you want, and the collateral it was holding frees up immediately.",
        "You are never locked in. You can repay part or all of the balance whenever you want.",
        "Borrowing more raises what you owe. It does not clear the loan faster.",
        "Withdrawing moves collateral out of the position, and only the part that is already free. Your balance stays exactly where it was.",
      ],
    },
    {
      prompt: "You open a loan and do not touch it for a year. Which description fits what happened to the balance?",
      options: [
        "It fell, and it never rose at any point along the way",
        "It rose steadily as interest was added",
        "It stayed flat, because nothing was repaid",
        "It rose and fell as the market moved",
      ],
      correct: 0,
      explain: [
        "Exactly. Nothing adds to the balance. Redemptions only ever pay it down.",
        "An Alchemix loan carries no interest. Nothing was added over the year.",
        "It did not stay flat. The protocol was repaying it the whole time.",
        "The balance does not track the market. It is recorded in alUSD or alETH and only moves as it is repaid.",
      ],
    },
  ],

  "what-can-go-wrong": [
    {
      prompt: "Which of these can put an Alchemix position at risk of liquidation?",
      options: [
        "A loss in the yield strategies holding your collateral",
        "A sharp fall in the price of ETH",
        "alUSD trading below 1.00 on an exchange",
        "Reaching the 90% borrowing cap",
      ],
      correct: 0,
      explain: [
        "Right. A real loss in the strategies behind your collateral is the one thing that can move you toward liquidation.",
        "A price fall moves your debt and your collateral together, so the ratio between them holds.",
        "The protocol values alAssets at face value for repayment, whatever an exchange is charging for them.",
        "Reaching the cap only stops further borrowing. The position stays open and keeps earning.",
      ],
    },
    {
      prompt: "Your position reaches the 90% borrowing cap. What happens next?",
      options: [
        "Borrowing stops. The position stays open and the collateral keeps earning",
        "The position is closed and your collateral is sold",
        "You are charged a fee until the ratio comes back down",
        "Part of your collateral is liquidated to bring the ratio down",
      ],
      correct: 0,
      explain: [
        "Yes. The cap limits borrowing and does nothing else.",
        "Nothing is closed or sold at the cap. It stops you borrowing more, and the position keeps earning.",
        "Sitting at the cap is free. Borrowing stops there and the position keeps earning.",
        "Nothing is liquidated at the cap. Liquidation is a separate mechanism, and it needs a loss of backing.",
      ],
    },
    {
      prompt: "Why can a swing in the price of your collateral not liquidate an Alchemix loan?",
      options: [
        "Your debt and your collateral are the same kind of asset, so they move together",
        "The protocol pauses positions during volatile markets",
        "Alchemix uses a fixed price for collateral instead of the market price",
        "An insurance fund absorbs price losses on behalf of borrowers",
      ],
      correct: 0,
      explain: [
        "Exactly. ETH backs alETH and USDC backs alUSD, so a price move changes both sides by the same amount and the ratio holds.",
        "Nothing is paused. The price move leaves the position exactly where it was.",
        "The price is not fixed or ignored. It applies to your debt and your collateral equally.",
        "There is no insurance fund doing this. A price move leaves both sides of your position in the same ratio, so there is no loss to absorb.",
      ],
    },
  ],

  "the-transmuter": [
    {
      prompt: "You put 5,000 alUSD into the Transmuter and wait the full term. What do you get back?",
      options: [
        "5,000 USDC worth, an exact 1:1 exchange",
        "5,000 USDC worth, minus an exchange fee",
        "Whatever 5,000 alUSD is trading for on the day it matures",
        "5,000 USDC worth, plus the yield earned while you waited",
      ],
      correct: 0,
      explain: [
        "Right. The exchange is exactly 1:1, and that guarantee is what holds the peg.",
        "Wait the full term and you keep the whole 1:1. A fee applies only if you leave before it is up.",
        "The market price does not apply. The Transmuter exchanges at 1:1 regardless of what an exchange is charging.",
        "Your alAssets do not earn while they wait. The return comes from buying below 1.00 and receiving 1.00 at maturity.",
      ],
    },
    {
      prompt: "What decides how long you wait for a Transmuter deposit to mature?",
      options: [
        "A term set by the Alchemix DAO, which varies by asset and chain",
        "The size of your deposit, with larger deposits taking longer",
        "How far below 1.00 the alAsset is currently trading",
        "The order deposits arrive in, with no fixed length",
      ],
      correct: 0,
      explain: [
        "Yes. The Alchemix DAO sets the term and adjusts it over time, so check the current one in the app before you deposit.",
        "Deposit size does not change the term. Everyone in the queue waits the same set duration.",
        "The market price does not set the term. The Alchemix DAO does.",
        "Deposits do queue, but the wait has a set length. Your place in line does not decide it.",
      ],
    },
    {
      prompt: "You need your funds back before your Transmuter deposit has matured. What are your options?",
      options: [
        "Exit early and pay an early transmutation fee, giving up part of the outcome",
        "Nothing. The deposit is locked until it matures",
        "Sell your place in the queue to another user",
        "Withdraw free of charge, as long as you do it in the first week",
      ],
      correct: 0,
      explain: [
        "Right. You can leave early whenever you need to, and the fee is what not waiting costs you.",
        "You are never locked in. Exit early whenever you need to, and the fee is what not waiting costs you.",
        "Queue positions are not traded between users. You exit your own deposit and pay the fee.",
        "There is no free window. The early transmutation fee applies whenever you leave before maturity.",
      ],
    },
  ],

  "getting-money-back": [
    {
      prompt:
        "A position holds 10,000 of collateral against 5,000 of debt, and the app shows " +
        "4,444 free to withdraw rather than 5,000. What is the other 556 doing?",
      options: [
        "Backing the debt, which needs 5,556 behind it to stay under the 90% cap",
        "Covering a fee charged when collateral leaves the position",
        "Held back until the next redemption cycle settles",
        "Earning yield that has not been credited to the position yet",
      ],
      correct: 0,
      explain: [
        "Yes. Debt can be at most 90% of collateral, so 5,000 of debt reserves 5,556. Everything above that is free.",
        "Withdrawing what is already free costs nothing. The gap is collateral the cap reserves, not a charge.",
        "Withdrawals are not on a cycle. You can take the free collateral any day, and what stays behind is set by the cap.",
        "Yield raises the value of the whole deposit. The gap is the collateral the 90% cap reserves against the debt.",
      ],
    },
    {
      prompt: "You repay 1,000 of an open loan. How much collateral does that free?",
      options: [
        "About 1,111, because each unit of debt reserves about 1.11 of collateral",
        "Exactly 1,000, one for one",
        "900, because the cap is 90%",
        "Nothing, until the loan is cleared in full",
      ],
      correct: 0,
      explain: [
        "Right. At a 90% cap, 1 of debt holds 1 / 0.9 of collateral, so clearing 1 of debt releases about 1.11.",
        "Repaying frees more than it clears. A unit of debt reserves 1.11 units of collateral, and that is what comes free.",
        "That inverts the cap. Debt is 90% of collateral, so collateral is 1 / 0.9 of debt: about 1.11.",
        "Collateral frees up with every repayment, not only once the last of the debt is gone.",
      ],
    },
    {
      prompt: "When can you withdraw the collateral the app shows as free?",
      options: [
        "Any day, with nothing to repay first",
        "Only once the loan is repaid in full",
        "Only at the end of a redemption cycle",
        "Only once the deposit has earned enough to cover the debt",
      ],
      correct: 0,
      explain: [
        "Right. Whatever the app shows as free can leave today. Repaying first is a choice, not a requirement.",
        "Repaying frees more collateral, but whatever is already free can leave today.",
        "Redemption cycles clear debt. They have nothing to do with when you can withdraw.",
        "Yield raises what the deposit is worth. What is free to withdraw is whatever sits above what the cap reserves.",
      ],
    },
    {
      prompt:
        "Two positions each hold 20,000 of collateral. One owes 5,000, the other owes 15,000. " +
        "Which has more free to withdraw?",
      options: [
        "The one owing 5,000, because a smaller debt reserves less collateral",
        "Both the same, because the cap applies to the collateral, not the debt",
        "The one owing 15,000, because a larger loan has drawn more yield",
        "Neither, because collateral is locked while any debt is open",
      ],
      correct: 0,
      explain: [
        "Yes. Reserved collateral is the debt divided by 0.9, so a smaller debt leaves more free.",
        "The cap ties the two together. What is reserved is set by the debt: 5,556 against 5,000, 16,667 against 15,000.",
        "Yield accrues to the deposit, not to the loan. It does not change what the cap reserves.",
        "Collateral above what the cap reserves is free at any time, whether or not debt is open.",
      ],
    },
  ],

  "pace-of-repayment": [
    {
      prompt:
        "Ana borrows 2,000 and Ben borrows 8,000 against identical deposits on the same day. " +
        "Both leave the position alone for a year. What is true at the end of it?",
      options: [
        "The same share of each loan is left, because one redemption rate applies to both",
        "Ana is further along, because a smaller loan clears sooner",
        "Ben is further along, because a larger loan draws more redemptions",
        "Neither has moved, because redemptions only run when you ask for them",
      ],
      correct: 0,
      explain: [
        "Right. The redemption rate is a share of debt, not an amount, so it applies to both loans equally.",
        "That is how an interest-bearing loan behaves. Alchemix charges no interest, and the rate is a share of what you owe.",
        "Redemptions are proportional. More of Ben's loan is cleared in absolute terms, but not a larger share of it.",
        "Redemptions run whether or not you touch the position. That is what makes the loan self-repaying.",
      ],
    },
    {
      prompt: "Which of these changes how fast redemptions clear your debt?",
      options: [
        "The redemption rate, which the protocol sets for the whole market",
        "The size of your loan",
        "The yield your vault earns",
        "The LTV you opened at",
      ],
      correct: 0,
      explain: [
        "Yes. It is the one input that moves the curve, and it is the same figure for every position in the market.",
        "Loan size changes the amount cleared, not the pace. The same share of a large loan and a small one goes each year.",
        "Yield raises what your MYT is worth. Redemptions are what clear the debt, and the two are separate.",
        "Your LTV sets how much room you have before a loss reaches you. It does not change the pace of repayment.",
      ],
    },
    {
      prompt: "The protocol raises the redemption rate. What happens to a position already open?",
      options: [
        "Its debt clears faster, at the new rate, along with every other position",
        "It keeps the rate it opened at, and only new positions use the new one",
        "Its collateral is sold faster to fund the difference",
        "Nothing, unless the borrower opts in",
      ],
      correct: 0,
      explain: [
        "Right. The rate is a protocol-level parameter applied to the whole market at once, not a term of your loan.",
        "There is no rate attached to a position. There is one rate, and it applies to everyone.",
        "Redemptions convert collateral already earmarked against the debt. Nothing extra is sold to keep up.",
        "There is nothing to opt in to. The rate applies to the whole market, and repaying by hand is the part you choose.",
      ],
    },
    {
      prompt: "You want the loan gone sooner than redemptions will clear it. What can you do?",
      options: [
        "Repay by hand, in any amount, whenever you like",
        "Raise the redemption rate on your own position",
        "Borrow more, which raises the rate applied to you",
        "Nothing. The pace is fixed for everyone",
      ],
      correct: 0,
      explain: [
        "Exactly. The rate is not yours to set, but repaying is always open and takes effect immediately.",
        "The rate is a market-wide parameter. There is no per-position setting for it.",
        "Borrowing more raises what you owe. It does not speed anything up.",
        "The rate is fixed for everyone, but repaying by hand is not.",
      ],
    },
  ],

  "where-yield-comes-from": [
      {
        prompt: "Why do the DAO's risk caps on an MYT matter to someone borrowing against it?",
        options: [
          "They bound the worst loss the vault can take, which is what makes a given LTV safe",
          "They cap how much you are allowed to borrow",
          "They set the yield your deposit earns",
          "They decide which asset you can repay with",
        ],
        correct: 0,
        explain: [
          "Right. A loss of backing is the one thing that can liquidate you, and the caps are what bound the size of a plausible one.",
          "Borrowing is capped at 90% of collateral. The risk caps govern what the vault may hold, not what you may take.",
          "The strategies set the yield. The caps limit how much of the riskiest ones the vault can hold.",
          "Which asset repays depends on whether the debt is earmarked. The risk caps are about vault composition.",
        ],
      },
      {
        prompt:
          "An MYT holds one strategy of each class, and Aggressive is filled to its 20% ceiling. " +
          "How much can the Moderate strategy hold?",
        options: [
          "40%, because Moderate and Aggressive share a 60% ceiling",
          "60%, because that is the Moderate ceiling",
          "20%, because Moderate can never hold more than Aggressive",
          "80%, because only Aggressive carries a cap",
        ],
        correct: 0,
        explain: [
          "Yes. The all-strategies figure covers that class and every riskier one, so the 60% is Moderate plus Aggressive.",
          "The 60% is shared. Aggressive is already inside it, so 40% is what remains for Moderate.",
          "There is no rule ordering the two. Moderate is bounded by its own 40% and by the 60% it shares with Aggressive.",
          "Both carry caps. Moderate is capped at 40% on its own and at 60% together with Aggressive.",
        ],
      },
      {
        prompt:
          "Three strategies are proposed: Conservative at 4%, Moderate at 7%, Aggressive at 15%. " +
          "Which composition pays most without breaching a cap?",
        options: [
          "40% Conservative, 40% Moderate, 20% Aggressive",
          "0% Conservative, 60% Moderate, 40% Aggressive",
          "20% Conservative, 40% Moderate, 40% Aggressive",
          "60% Conservative, 20% Moderate, 20% Aggressive",
        ],
        correct: 0,
        explain: [
          "Right. Aggressive fills its 20%, Moderate takes the 40% left of the shared 60%, and Conservative absorbs the rest.",
          "Aggressive is capped at 20%, and Moderate and Aggressive together at 60%. This breaches both.",
          "Aggressive is capped at 20%. Doubling it is not something the DAO could allocate.",
          "This one is legal but not the best available: Moderate can go to 40% before the shared ceiling binds.",
        ],
      },
      {
        prompt:
          "A run of withdrawals shrinks an MYT until its Aggressive strategy is 24% of what is left, " +
          "above the 20% cap. What follows?",
        options: [
          "The allocation stays above its cap until the DAO rebalances, because caps are checked when the DAO allocates",
          "The vault is sold down to the cap automatically",
          "Withdrawals are blocked until the composition is legal again",
          "Nothing, because the caps only apply when an MYT is first created",
        ],
        correct: 0,
        explain: [
          "Exactly. The caps are relative to vault size and are enforced at allocation, so a shrinking vault can drift above one.",
          "Nothing sells automatically. Rebalancing is a DAO action.",
          "Withdrawals are never gated on composition. Your collateral stays yours to take.",
          "The caps govern every allocation, not just the first. They are simply not re-checked on every withdrawal.",
        ],
      },
    ],

  "cost-of-borrowing": [
    {
      prompt: "You want 10,000 of spendable USDC, and alUSD is trading at 0.98. What do you borrow?",
      options: [
        "More than 10,000, because each alUSD sells for less than a dollar",
        "Exactly 10,000, because debt is recorded at face value",
        "Less than 10,000, because the discount works in your favor",
        "10,000, with the discount charged later as a fee",
      ],
      correct: 0,
      explain: [
        "Right. At 0.98 you need about 10,204 alUSD to walk away with 10,000, and 10,204 is the debt recorded.",
        "Debt is recorded at face value, which is exactly why you have to borrow more than you want to raise.",
        "The discount is a cost to a borrower and a gain to a buyer. You are the one selling below par.",
        "Nothing is charged later. You simply receive less than face value when you sell.",
      ],
    },
    {
      prompt: "You mint 1,000 alUSD and sell it at 0.97. What debt is recorded against your position?",
      options: [
        "1,000, because debt is recorded at face value whatever you sold for",
        "970, the amount you actually received",
        "1,030, so the discount is covered",
        "It depends on what alUSD is trading at when you repay",
      ],
      correct: 0,
      explain: [
        "Yes. The market price is between you and the buyer. Inside Alchemix, 1 alUSD is always 1 of debt.",
        "You received 970, but you minted 1,000, and 1,000 is what the position owes.",
        "Nothing is added. The discount is what you gave up on the sale, not something charged on top.",
        "The price never enters it. One alUSD cancels one of debt on any day, at any price.",
      ],
    },
    {
      prompt: "What does an Alchemix loan charge you for holding it longer?",
      options: [
        "Nothing. There is no interest and no charge for time",
        "A variable rate the DAO sets each period",
        "A fixed rate agreed when you borrow",
        "A rate that rises as your LTV rises",
      ],
      correct: 0,
      explain: [
        "Right. Time only works in your favor here: redemptions clear the balance while the collateral earns.",
        "There is no rate of any kind. What the DAO sets is the redemption rate, which clears debt rather than adding to it.",
        "No rate is agreed. The costs are the discount when you sell and the fees tied to specific events.",
        "LTV governs your borrowing room and your distance from the threshold. It does not price the loan.",
      ],
    },
    {
      prompt: "Which of these is a real cost of borrowing in Alchemix?",
      options: [
        "The discount you take when you sell alUSD below face value",
        "Interest accruing on the balance",
        "A daily fee while the position stays open",
        "A penalty for repaying early",
      ],
      correct: 0,
      explain: [
        "Exactly. It is paid once, up front, in the gap between what you mint and what you receive.",
        "There is none. The balance never rises unless you borrow again.",
        "Costs here are tied to events, never to the calendar. Holding a position costs nothing.",
        "Repaying early is free and frees collateral immediately. There is no penalty for it.",
      ],
    },
  ],

  "ltv-and-risk": [
    {
      prompt: "What should decide the highest LTV you open at?",
      options: [
        "The largest loss of backing the vault could plausibly take, which the DAO's risk caps bound",
        "How far you expect the price of your collateral to fall",
        "The redemption rate, since it sets how fast you deleverage",
        "The 90% borrowing cap, which is also the liquidation threshold",
      ],
      correct: 0,
      explain: [
        "Right. A loss of backing is the only thing that can reach you, and the caps are what make that worst case finite.",
        "Price cannot liquidate an Alchemix position. Debt and collateral are the same kind of asset and move together.",
        "The rate sets how quickly the debt clears. It has no bearing on how much loss you can absorb.",
        "They are different numbers. The cap is 90% and stops further borrowing; liquidation begins at 95%.",
      ],
    },
    {
      prompt: "Your position sits at 50% LTV and the MYT reports a 20% loss of backing. What follows?",
      options: [
        "Your LTV moves to 62.5% and the position is untouched, because the threshold is still above it",
        "You are liquidated, because any loss of backing crosses the threshold",
        "Nothing changes, because a loss inside the vault does not affect your LTV",
        "Your debt is written down by 20% to match the collateral",
      ],
      correct: 0,
      explain: [
        "Yes. The same debt now stands against 80% of the collateral, and 50 / 0.8 is 62.5, well under the 95% threshold.",
        "Only a loss large enough to push your LTV past 95% does that. At 50% you have a lot of room.",
        "It does. Your collateral is worth less while the debt is unchanged, so the ratio between them moves.",
        "Debt is unchanged by a loss of backing. That is exactly why the ratio moves against you.",
      ],
    },
    {
      prompt: "A position does cross the liquidation threshold. What does the protocol sell?",
      options: [
        "Only enough to bring the position back to a safe ratio",
        "The whole deposit, closing the position",
        "Enough to clear the debt in full",
        "Nothing, until the borrower chooses to act",
      ],
      correct: 0,
      explain: [
        "Right. It is the minimum needed to restore a healthy LTV, and everything above that is untouched.",
        "Nothing forces a position to close. What is sold is the minimum that restores a safe ratio.",
        "The debt is not cleared. Enough collateral is used to bring the ratio back under the cap, and no more.",
        "Past the threshold the protocol acts without waiting. What it sells is the minimum, not everything.",
      ],
    },
    {
      prompt: "Why can a 40% fall in the price of ETH not liquidate an alETH loan?",
      options: [
        "Debt and collateral are the same kind of asset, so both sides fall together and the ratio holds",
        "The protocol pauses liquidations while the market is moving sharply",
        "The oracle averages the price over a long enough window to absorb it",
        "The 90% cap leaves enough room to absorb a fall that size",
      ],
      correct: 0,
      explain: [
        "Exactly. 4 ETH behind 2 alETH is a 50% LTV at any price, because the price divides out of both sides.",
        "Nothing is paused. The ratio simply does not move when the price does.",
        "No averaging is needed. Both sides are denominated in the same asset, so the ratio is price-independent.",
        "Room is not what saves you. Even a 90% fall would leave the LTV exactly where it started.",
      ],
    },
  ],

  "transmuter-and-peg": [
    {
      prompt:
        "alUSD is trading at 0.97 and redeems 1:1 at maturity. One market has a 10-week term and " +
        "another a 30-week term. Which pays more, annualized?",
      options: [
        "The 10-week term, because the same discount is collected three times as often",
        "The 30-week term, because you are paid for waiting longer",
        "The same, because the discount is the same",
        "Neither. The Transmuter pays a rate the DAO sets, not one the discount sets",
      ],
      correct: 0,
      explain: [
        "Right. The gain per term is identical, so the shorter wait is worth three times as much over a year.",
        "Waiting longer for the same 3.09% is worth less per year, not more.",
        "The gain over one term is the same. Annualized, how long you wait for it is the whole difference.",
        "The DAO sets the term. What you earn is set by the price you buy at, which is why a wider discount pays more.",
      ],
    },
    {
      prompt: "Why does alUSD trading below a dollar tend to pull the price back up?",
      options: [
        "The Transmuter guarantees 1:1 at maturity, so a wide discount pays well enough to attract buyers",
        "The DAO buys alUSD on the open market whenever it trades below par",
        "The protocol stops minting alUSD until the price recovers",
        "Borrowers are charged a fee whenever the price is below par",
      ],
      correct: 0,
      explain: [
        "Yes. The wider the gap, the better the fixed return for waiting it out, and that buying is what closes it.",
        "No one is required to buy. The peg holds because waiting out the term pays, not because of intervention.",
        "Minting is not gated on the price. What restores the price is buyers taking the discount.",
        "No such fee exists. The discount is a cost a borrower takes when selling, not an ongoing charge.",
      ],
    },
    {
      prompt: "You hold alUSD and you also have an open Alchemix loan. What is the direct way to use it?",
      options: [
        "Repay the loan with it. One alUSD cancels one of debt, immediately",
        "Deposit it in the Transmuter and wait out the term for USDC",
        "Sell it on Curve, then repay with the USDC",
        "Either route is the same, since both settle 1:1",
      ],
      correct: 0,
      explain: [
        "Right. The Transmuter is a fixed-yield product for savers. A borrower holding alUSD already holds what cancels the debt.",
        "That is the saver's route. It would mean waiting out a term for USDC while still carrying the debt.",
        "Selling means taking the discount on something you could have used to repay directly.",
        "They are not the same. Repaying settles today, and the Transmuter settles at the end of a term.",
      ],
    },
    {
      prompt: "What actually backs the Transmuter's 1:1 exchange?",
      options: [
        "Borrower collateral inside the Alchemist, earmarked against the alUSD waiting in the queue",
        "A reserve the DAO funds out of protocol fees",
        "Liquidity in external pools such as Curve and Balancer",
        "New alUSD minted when a redemption comes due",
      ],
      correct: 0,
      explain: [
        "Exactly. Every alAsset in the queue earmarks an equal value of collateral, and at maturity that collateral settles the claim.",
        "There is no separate reserve. The backing is the collateral of borrowers whose debt the redemption repays.",
        "External pools give you the market price today. The 1:1 guarantee comes from collateral inside the protocol.",
        "Minting more would defeat the point. Redemptions burn alUSD, they do not create it.",
      ],
    },
  ],

  "capstone": [
    {
      prompt:
        "You want a fixed amount of spendable capital, alUSD trades below par, and the vault could " +
        "lose backing. Which two things set the smallest deposit you can open with?",
      options: [
        "How much you must borrow once the discount is accounted for, and the highest LTV that survives the loss",
        "The redemption rate and the length of the transmutation term",
        "The price of your collateral and the 90% borrowing cap",
        "The vault's blended APR and the redemption fee",
      ],
      correct: 0,
      explain: [
        "Right. The deposit is the borrow you need, divided by the LTV that survives the loss.",
        "Those govern how fast the debt clears afterwards. Neither changes the size you have to open at.",
        "Price does not enter it: debt and collateral move together. The loss is what limits you, not the cap.",
        "Both are real, and neither sizes the position. They affect what it earns and what deleveraging costs.",
      ],
    },
    {
      prompt: "alUSD is trading lower than you assumed. What happens to the deposit you need?",
      options: [
        "It rises, because you have to borrow more alUSD to raise the same cash",
        "It falls, because your debt is worth less on the market",
        "Nothing, because the deposit is set by the loss you are sizing against",
        "It rises, because a low price raises the liquidation threshold",
      ],
      correct: 0,
      explain: [
        "Yes. A wider discount means more debt for the same cash, and more debt needs more collateral behind it.",
        "Debt is recorded at face value. What it trades at does not reduce what you owe.",
        "The loss sets the LTV you can carry. The price sets how much you must borrow, and both move the deposit.",
        "The threshold is fixed at 95%. The price moves how much you borrow, not where liquidation sits.",
      ],
    },
    {
      prompt: "The loss you are sizing against doubles. What happens to the LTV you can safely open at?",
      options: [
        "It falls, so the same borrow needs a larger deposit behind it",
        "It rises, because a larger loss frees more collateral",
        "Nothing, because the liquidation threshold is fixed at 95%",
        "It falls, and the 90% borrowing cap falls with it",
      ],
      correct: 0,
      explain: [
        "Right. The threshold applies to the backing that survives, so a larger loss leaves less room to start with.",
        "A loss reduces backing. It never frees collateral.",
        "The threshold is fixed, but the collateral it applies to is not. A larger loss leaves less of it.",
        "The borrowing cap does not move. What moves is how much of it you can safely use.",
      ],
    },
    {
      prompt: "Three of these change the deposit you need. Which one does not?",
      options: [
        "A fall in the market price of your collateral",
        "A wider discount on alUSD",
        "A larger loss of MYT backing",
        "A larger amount of capital you want to raise",
      ],
      correct: 0,
      explain: [
        "Exactly. Price moves debt and collateral together, so it cancels out of the sizing entirely.",
        "A wider discount does move it: you borrow more to raise the same cash, so you deposit more.",
        "A larger loss does move it: the survivable LTV falls, so the same borrow needs more behind it.",
        "Raising more capital does move it: more borrow, and proportionally more deposit.",
      ],
    },
  ],
};

/**
 * The same deterministic shuffle the engine uses, so a locally generated question
 * behaves the way the deployed one does.
 *
 * Returns display position to original index.
 */
export function permutation(n, seed) {
  const order = Array.from({ length: n }, (_, i) => i);

  let state = (Math.abs(Math.trunc(seed)) % 2147483647) + 1;
  const next = () => {
    state = (state * 1664525 + 1013904223) % 4294967296;
    return state / 4294967296;
  };

  for (let i = n - 1; i > 0; i -= 1) {
    const j = Math.floor(next() * (i + 1));
    [order[i], order[j]] = [order[j], order[i]];
  }
  return order;
}
